language: go
sudo: false
go:
  - "1.5"

install:
  - 'bundle install'
  - 'pip install --user linkchecker'
  - 'make clean'
  - 'make themes'
  - 'make travis-server &'
  - 'sleep 10'

script:
  - 'make travis-linkchecker'
  - 'make generate'

notifications:
  email: false
  irc:
    secure: "YbNlEsQzKnA+8UJMpVOyG6z3rxYqzZIoRGgxv5MPfvQqxSh+koZVgycRtl9/1hyr7Z+IwqEWv97ky+1bU2kxcfKWpEAclK7+tsLsCcxrcw9q9pX9vU7gVV8Ds+MKAL8R0VHTXWBzVboJ3Upt1lCpNSx89YjZ8JwFJnYFfWrAPejogK8IqCPVs1yK3txqyUlJz6QUqJ/uAfg02+6Kq4y7wGMleG7CE1Erl05EE3VvqWoErMaZoWCLmqL1Yq58wheF/F52Jb+vrEK94aM6DV7cDycAQlfZHdwdjI2Wj8Ri+ssvK/g27DPQ7EBwr2wVap4AgWcOBnBtpERZw742X/vDyWNm9yaKo7ag7u2iBQrppg0R4R2cLB+njCKucxv4gfmj6FmEMW6FotIIqAe66lmlHuZAg/lau+59JPVun8qRT4qfJq7u4Nld8DXxNGGor+4ljAyja/n/TXty8h5vFuA4LpAwuB2f2RL4HZC/BZekHd4kXD5ixHcehdJDKr9b0lNshR39cunhKp4xL59MnB7mdhSah9VVh84ohVQvSDhVooOI+4JaZRSXHOCBIYXTKQiGya2O3stIh3ul3uyRM0I+mSC6F+jmgJgP538NnduyJxP4axWGroAgdhQprZgn2Mr4cwDlrfILawn5DTFeNxLFTYuRwxBiRt/MLZi9wJ7rn/w="
