language: go
sudo: false
go:
  - "1.5"

env:
  global:
    - 'AWS_ACCESS_KEY_ID=AKIAJP3DIYUEHRAW7A6A'
    - secure: "INDj5AOKacxWOCgqP8CwimbpqYItBXOgTDw5/Idq8sfVdyRtVhoiP6v+9h244/t3JIMppRcTrYYW1/DY1JYOzZqdcdukQ5KxfC0RpIzFuc/LlrAKQx9ubrnXSdW/w2E+Fn6Wj80cJn1ksJJPuFXaG8ksjKHP7eLDteUkjlMr+48NhoTvmlbtSzlvquwaZmGjacWyUgVpjbLdn5n3KrYDMLxQM8byoSHyUeuLNNX6hXTuz1JaSmclmlPH361+ch60JOfEtSD0mGetv+KlCnfWBQf3UhXdeCLQFX64d+PYUfcwibox8VRix6I96CqAbeqRjqlP7y38FufGnDN1iYFvIVnvH4jg//eapO21oPD+tHHkUu8O0SHltHjeibZQcDW6edG74uRqSD1Jg1shFEL1tR2V/y6UsnnmcTF1ruXJM0q58dQ4dSZHf8zxdPezWXaUZAr4B/fTMjSe1vm0qEFJuA3YWLMY2ChxTKOCGFFRjDDk7olmFWf3GrHOazJk9CkMkWPxmz8mGghHALV7UV8QIGJP44WX1oYaEflf723tIQQ063fjPYCf0e3bPrXy9ozjk3Ff0etyyzgBdS0ZEl51cd3PCBn4zFKIzt4TqO95og9gMf6u7/uTquq7r80KpoGLVW3gsI6Qda6Nxy4dd3H4x7HIyxETG21rO6iwXg4x1Cc="

install:
  - 'bundle install'
  - 'pip install --user linkchecker'
  - 'make clean'
  - 'make themes'
  - 'make travis-server &'
  - 'sleep 10'

script:
  - 'make travis-linkchecker'
  - 'make generate'

deploy:
  provider: 'script'
  script: 'bundle exec s3_website push --verbose'
  skip_cleanup: true
  on:
    branch: 'master'
    repo: 'marvinpinto/charlesbot.org'

notifications:
  email: false
  irc:
    secure: "YbNlEsQzKnA+8UJMpVOyG6z3rxYqzZIoRGgxv5MPfvQqxSh+koZVgycRtl9/1hyr7Z+IwqEWv97ky+1bU2kxcfKWpEAclK7+tsLsCcxrcw9q9pX9vU7gVV8Ds+MKAL8R0VHTXWBzVboJ3Upt1lCpNSx89YjZ8JwFJnYFfWrAPejogK8IqCPVs1yK3txqyUlJz6QUqJ/uAfg02+6Kq4y7wGMleG7CE1Erl05EE3VvqWoErMaZoWCLmqL1Yq58wheF/F52Jb+vrEK94aM6DV7cDycAQlfZHdwdjI2Wj8Ri+ssvK/g27DPQ7EBwr2wVap4AgWcOBnBtpERZw742X/vDyWNm9yaKo7ag7u2iBQrppg0R4R2cLB+njCKucxv4gfmj6FmEMW6FotIIqAe66lmlHuZAg/lau+59JPVun8qRT4qfJq7u4Nld8DXxNGGor+4ljAyja/n/TXty8h5vFuA4LpAwuB2f2RL4HZC/BZekHd4kXD5ixHcehdJDKr9b0lNshR39cunhKp4xL59MnB7mdhSah9VVh84ohVQvSDhVooOI+4JaZRSXHOCBIYXTKQiGya2O3stIh3ul3uyRM0I+mSC6F+jmgJgP538NnduyJxP4axWGroAgdhQprZgn2Mr4cwDlrfILawn5DTFeNxLFTYuRwxBiRt/MLZi9wJ7rn/w="
